#!/bin/sh
# Camel case input string

# Example 1. Camel case a string.
# $ echo "foo_bar" | camelcase
# output: fooBar

# Example 2: Camel case all lines in a file
# cat file.txt | camelcase 

_camelcase() {
        echo $1 | perl -pe 's/(^|_)./uc($&)/ge;s/_//g' | sed 's/.*/\l&/'
}

if test -n "$1";
    then
        _camelcase "$1"
    else
        while read arg; do _camelcase "$arg"; done;
fi

