#!/bin/sh
# Replace space, underscore with dash

_dash() {
        echo $1 | sed 's/ /-/g' | sed 's/_/-/g' 
}

if test -n "$1";
    then
        _dash "$1"
    else
        while read arg; do _dash "$arg"; done;
fi

