#!/bin/sh
# Change hex to dec

_hex2dec() {
        echo $1 | awk '{print toupper($0)}' | awk '{ print "echo \"ibase=16;"$1"\" | bc"}' | sh
}

if test -n "$1";
    then
        _hex2dec "$1"
    else
        while read arg; do _hex2dec "$arg"; done;
fi

