#!/bin/sh
# Snake case input string

# Example 1. Snake case a string.
# $ echo "FooBar" | snakecase
# output: foo_bar

# Example 2: Snake case all lines in a file
# cat file.txt | snakecase 

_snakecase() {
        echo $1 | sed 's/\(.\)\([A-Z]\)/\1_\2/g' | tr '[:upper:]' '[:lower:]'
}

if test -n "$1";
    then
        _snakecase "$1"
    else
        while read arg; do _snakecase "$arg"; done;
fi

