#!/bin/sh
# Replace underscore, dash iccurences with space

_space() {
        echo $1 | sed 's/_/ /g' | sed 's/-/ /g' 
}

if test -n "$1";
    then
        _space "$1"
    else
        while read arg; do _space "$arg"; done;
fi

