#!/bin/sh
# Replace space, dash iccurences with underscore

_underscore() {
        echo $1 | sed 's/ /_/g' | sed 's/-/_/g' 
}

if test -n "$1";
    then
        _underscore "$1"
    else
        while read arg; do _underscore "$arg"; done;
fi

